/**
 * Catalogo de codigos de erro — UPPER_SNAKE_CASE.
 * Fonte: docs/backend/09-errors.md
 * Frontend usa estes codigos para decidir como exibir o erro.
 */
export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  CLUSTER_NOT_FOUND = 'CLUSTER_NOT_FOUND',
  MEMBER_NOT_FOUND = 'MEMBER_NOT_FOUND',
  NODE_NOT_FOUND = 'NODE_NOT_FOUND',
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  MEMBER_ALREADY_EXISTS = 'MEMBER_ALREADY_EXISTS',
  INVITE_ALREADY_EXISTS = 'INVITE_ALREADY_EXISTS',
  DUPLICATE_FILE = 'DUPLICATE_FILE',
  INSUFFICIENT_NODES = 'INSUFFICIENT_NODES',
  INVALID_SEED_PHRASE = 'INVALID_SEED_PHRASE',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  CLUSTER_FULL = 'CLUSTER_FULL',
  INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  INSUFFICIENT_REPLICATION = 'INSUFFICIENT_REPLICATION',
  STORAGE_PROVIDER_ERROR = 'STORAGE_PROVIDER_ERROR',
  EMAIL_SERVICE_ERROR = 'EMAIL_SERVICE_ERROR',
  FFMPEG_ERROR = 'FFMPEG_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
